# Generated by Django 3.2.2 on 2021-05-18 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('englishapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='englishapp.word', verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.TextField(unique=True, verbose_name='問題'),
        ),
        migrations.AlterField(
            model_name='word',
            name='english',
            field=models.CharField(max_length=100, verbose_name='カテゴリ名'),
        ),
        migrations.AlterField(
            model_name='word',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
