# Generated by Django 3.2.3 on 2021-05-20 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('englishapp', '0002_auto_20210518_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='category',
        ),
    ]
